version: "3.9"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: shiva
      POSTGRES_PASSWORD: shiva1234
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
